train_ds:
  manifest_filepath: /Users/xujinghua/speaker-reco/data/train.json
  sample_rate: 16000
  labels: null
  batch_size: 64
  shuffle: true
  time_length: 8
  is_tarred: false
  tarred_audio_filepaths: null
  tarred_shard_strategy: scatter
validation_ds:
  manifest_filepath: /Users/xujinghua/speaker-reco/data/dev.json
  sample_rate: 16000
  labels: null
  batch_size: 128
  shuffle: false
  time_length: 8
test_ds:
  manifest_filepath: /Users/xujinghua/speaker-reco/data/test_jxu.json
  sample_rate: 16000
  labels: null
  batch_size: 1
  shuffle: false
  time_length: 8
  embedding_dir: .
preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  normalize: per_feature
  window_size: 0.02
  sample_rate: 16000
  window_stride: 0.01
  window: hann
  features: 64
  n_fft: 512
  frame_splicing: 1
  dither: 1.0e-05
  stft_conv: false
encoder:
  _target_: nemo.collections.asr.modules.ConvASREncoder
  feat_in: 64
  activation: relu
  conv_mask: true
  jasper:
  - filters: 512
    repeat: 1
    kernel:
    - 3
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.5
    residual: true
    separable: true
  - filters: 512
    repeat: 2
    kernel:
    - 7
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.5
    residual: true
    separable: true
  - filters: 512
    repeat: 2
    kernel:
    - 11
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.5
    residual: true
    separable: true
  - filters: 512
    repeat: 2
    kernel:
    - 15
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.5
    residual: true
    separable: true
  - filters: 1500
    repeat: 1
    kernel:
    - 1
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: false
    separable: true
decoder:
  _target_: nemo.collections.asr.modules.SpeakerDecoder
  feat_in: 1500
  num_classes: 75
  pool_mode: xvector
  emb_sizes: 512,512
  angular: false
loss:
  scale: 30
  margin: 0.2
optim:
  name: novograd
  lr: 0.006
  args:
    name: auto
    betas:
    - 0.95
    - 0.5
    weight_decay: 0.001
  sched:
    name: CosineAnnealing
    iters_per_batch: 1
    max_steps: null
    args:
      name: auto
      warmup_steps: null
      warmup_ratio: 0.1
      min_lr: 0.0
      last_epoch: -1
target: nemo.collections.asr.models.label_models.EncDecSpeakerLabelModel
